<?php

namespace Database\Factories;

use App\Enums\OrganizationStatus;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Organization>
 */
class OrganizationFactory extends Factory
{
    public function definition(): array
    {
        return [
            'name' => fake()->company(),
            'slug' => null, // Will be auto-generated by model boot
            'owner_id' => User::factory(),
            'billing_email' => fake()->companyEmail(),
            'status' => OrganizationStatus::Active,
            'max_members' => fake()->numberBetween(5, 50),
            'settings' => [
                'allow_member_invites' => true,
                'require_two_factor' => false,
            ],
        ];
    }

    public function inactive(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => OrganizationStatus::Inactive,
        ]);
    }

    public function suspended(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => OrganizationStatus::Suspended,
        ]);
    }

    public function ownedBy(User $user): static
    {
        return $this->state(fn (array $attributes) => [
            'owner_id' => $user->id,
        ]);
    }
}
